=== caotoan02072004/BTL_XML/bin/btl.xsd
<?xml version="1.0" encoding="UTF-8"?> <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Employee_id" type="xs:positiveInteger"></xs:element>
    <xs:element name="First_name">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="2"></xs:minLength>
                <xs:maxLength value="50"></xs:maxLength>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="Last_name">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="2"></xs:minLength>
                <xs:maxLength value="50"></xs:maxLength>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="Email">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[^\s@]+@[^\s]+\.[^\s]{2,3}"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="Phone_number">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="[0-9]{10}"></xs:pattern>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="Date" type="xs:date"></xs:element>
    <xs:element name="Job_id">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="0"></xs:minInclusive>
                <xs:maxInclusive value="15"></xs:maxInclusive>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="Salary">
        <xs:simpleType>
            <xs:restriction base="xs:positiveInteger">
                <xs:minInclusive value="900"></xs:minInclusive>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:simpleType name="formatManagerID">
        <xs:restriction base="xs:string">
            <xs:pattern value="[\s\w\n]*"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="Manager_id">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="formatManagerID">
                    <xs:attribute name="note" use="optional"></xs:attribute>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="Employee">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Employee_id"></xs:element>
                <xs:element ref="First_name"></xs:element>
                <xs:element ref="Last_name"></xs:element>
                <xs:element ref="Email"></xs:element>
                <xs:element ref="Phone_number"></xs:element>
                <xs:element ref="Date"></xs:element>
                <xs:element ref="Job_id"></xs:element>
                <xs:element ref="Salary"></xs:element>
                <xs:element ref="Manager_id"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Employees">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Employee" minOccurs="1" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueId">
            <xs:selector xpath="Employee/Employee_id"></xs:selector>
            <xs:field xpath="."></xs:field>
        </xs:unique>
    </xs:element>
</xs:schema>

=== caotoan02072004/BTL_XML/bin/btl.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="yc1.xsl" type="text/xsl"?>
<!-- <?xml-stylesheet href="yc2.xsl" type="text/xsl"?> -->
<!-- <?xml-stylesheet href="yc3.xsl" type="text/xsl"?> -->
<!-- <?xml-stylesheet href="yc4.xsl" type="text/xsl"?> -->
<!-- <?xml-stylesheet href="yc5.xsl" type="text/xsl"?> -->
<Employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="btl.xsd">
    <Employee>
        <Employee_id>100</Employee_id>
        <First_name>Nguyễn</First_name>
        <Last_name>Luận</Last_name>
        <Email>luannv@gmail.com</Email>
        <Phone_number>0339513645</Phone_number>
        <Date>2018-01-01</Date>
        <Job_id>1</Job_id>
        <Salary>2000000</Salary>
        <Manager_id>105</Manager_id>
    </Employee>
    <Employee>
        <Employee_id>101</Employee_id>
        <First_name>Nguyễn</First_name>
        <Last_name>Năng</Last_name>
        <Email>nang@gmail.com</Email>
        <Phone_number>0339513642</Phone_number>
        <Date>2022-01-01</Date>
        <Job_id>2</Job_id>
        <Salary>3000000</Salary>
        <Manager_id>108</Manager_id>
    </Employee>
    <Employee>
        <Employee_id>102</Employee_id>
        <First_name>Nguyễn</First_name>
        <Last_name>Hiền</Last_name>
        <Email>hienpx@gmail.com</Email>
        <Phone_number>0339513643</Phone_number>
        <Date>2020-01-08</Date>
        <Job_id>1</Job_id>
        <Salary>2000000</Salary>
        <Manager_id>108</Manager_id>
    </Employee>
    <Employee>
        <Employee_id>103</Employee_id>
        <First_name>Nguyễn</First_name>
        <Last_name>Lương</Last_name>
        <Email>luong@gmail.com</Email>
        <Phone_number>0339513641</Phone_number>
        <Date>2020-01-09</Date>
        <Job_id>1</Job_id>
        <Salary>2000000</Salary>
        <Manager_id>202</Manager_id>
    </Employee>
    <Employee>
        <Employee_id>108</Employee_id>
        <First_name>Nguyễn</First_name>
        <Last_name>Toàn</Last_name>
        <Email>toan@gmail.com</Email>
        <Phone_number>0353915618</Phone_number>
        <Date>2020-01-09</Date>
        <Job_id>1</Job_id>
        <Salary>3500000</Salary>
        <Manager_id>201</Manager_id>
    </Employee>
</Employees>
